import { Link } from '@/i18n/navigation';
import { setRequestLocale } from 'next-intl/server';
import { ChevronLeft } from 'lucide-react';

export default async function PrivacyPolicyPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="max-w-4xl mx-auto px-4 md:px-6 py-16">
      <Link
        href="/docs/terms"
        className="inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8"
      >
        <ChevronLeft className="w-4 h-4" />
        Terms of Use
      </Link>

      <h1 className="text-3xl md:text-4xl font-bold mb-2">Privacy Policy</h1>
      <p className="text-muted-foreground mb-8">Effective date: October 03, 2018</p>

      <div className="prose prose-neutral dark:prose-invert max-w-none">
        <p>
          UniPad (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the UniPad mobile
          application (hereinafter referred to as the &quot;Service&quot;).
        </p>
        <p>
          This page informs you of our policies regarding the collection, use, and disclosure of
          personal data when you use our Service and the choices you have associated with that data.
        </p>
        <p>
          We use your data to provide and improve the Service. By using the Service, you agree to
          the collection and use of information in accordance with this policy.
        </p>

        <h2>Definitions</h2>
        <ul>
          <li>
            <strong>Service</strong> — the UniPad mobile application operated by UniPad.
          </li>
          <li>
            <strong>Personal Data</strong> — data about a living individual who can be identified
            from those data (or from those and other information either in our possession or likely
            to come into our possession).
          </li>
          <li>
            <strong>Usage Data</strong> — data collected automatically either generated by the use
            of the Service or from the Service infrastructure itself (for example, the duration of a
            page visit).
          </li>
          <li>
            <strong>Cookies</strong> — small files stored on your device (computer or mobile
            device).
          </li>
          <li>
            <strong>Data Controller</strong> — the natural or legal person who (either alone or
            jointly or in common with other persons) determines the purposes for which and the
            manner in which any personal information are, or are to be, processed. For the purpose
            of this Privacy Policy, we are a Data Controller of your Personal Data.
          </li>
          <li>
            <strong>Data Processors (or Service Providers)</strong> — any natural or legal person
            who processes the data on behalf of the Data Controller. We may use the services of
            various Service Providers in order to process your data more effectively.
          </li>
          <li>
            <strong>Data Subject (or User)</strong> — any living individual who is using our Service
            and is the subject of Personal Data.
          </li>
        </ul>

        <h2>Information Collection and Use</h2>
        <p>
          We collect several different types of information for various purposes to provide and
          improve our Service to you.
        </p>

        <h3>Types of Data Collected</h3>

        <h4>Personal Data</h4>
        <p>
          While using our Service, we may ask you to provide us with certain personally identifiable
          information that can be used to contact or identify you (&quot;Personal Data&quot;).
          Personally identifiable information may include, but is not limited to:
        </p>
        <ul>
          <li>Email address</li>
          <li>Cookies and Usage Data</li>
        </ul>

        <h4>Usage Data</h4>
        <p>
          When you access the Service with a mobile device, we may collect certain information
          automatically, including, but not limited to, the type of mobile device you use, your
          mobile device unique ID, the IP address of your mobile device, your mobile operating
          system, the type of mobile Internet browser you use, unique device identifiers and other
          diagnostic data (&quot;Usage Data&quot;).
        </p>

        <h4>Cookies</h4>
        <p>
          We use cookies and similar tracking technologies to track the activity on our Service and
          we hold certain information.
        </p>
        <p>
          Cookies are files with a small amount of data which may include an anonymous unique
          identifier. Cookies are sent to your browser from a website and stored on your device.
          Other tracking technologies are also used such as beacons, tags and scripts to collect and
          track information and to improve and analyze our Service.
        </p>
        <p>
          You can instruct your browser to refuse all cookies or to indicate when a cookie is being
          sent. However, if you do not accept cookies, you may not be able to use some portions of
          our Service.
        </p>

        <h2>Use of Data</h2>
        <p>UniPad uses the collected data for various purposes:</p>
        <ul>
          <li>To provide and maintain our Service</li>
          <li>To notify you about changes to our Service</li>
          <li>
            To allow you to participate in interactive features of our Service when you choose to do
            so
          </li>
          <li>To provide customer support</li>
          <li>To gather analysis or valuable information so that we can improve our Service</li>
          <li>To monitor the usage of our Service</li>
          <li>To detect, prevent and address technical issues</li>
        </ul>

        <h2>
          Legal Basis for Processing Personal Data under the General Data Protection Regulation
          (GDPR)
        </h2>
        <p>
          If you are from the European Economic Area (EEA), UniPad&apos;s legal basis for collecting
          and using the personal information described in this Privacy Policy depends on the Personal
          Data we collect and the specific context in which we collect it.
        </p>
        <p>UniPad may process your Personal Data because:</p>
        <ul>
          <li>We need to perform a contract with you</li>
          <li>You have given us permission to do so</li>
          <li>The processing is in our legitimate interests and it&apos;s not overridden by your rights</li>
          <li>For payment processing purposes</li>
          <li>To comply with the law</li>
        </ul>

        <h2>Retention of Data</h2>
        <p>
          UniPad will retain your Personal Data only for as long as is necessary for the purposes
          set out in this Privacy Policy. We will retain and use your Personal Data to the extent
          necessary to comply with our legal obligations (for example, if we are required to retain
          your data to comply with applicable laws), resolve disputes and enforce our legal
          agreements and policies.
        </p>
        <p>
          UniPad will also retain Usage Data for internal analysis purposes. Usage Data is generally
          retained for a shorter period of time, except when this data is used to strengthen the
          security or to improve the functionality of our Service, or we are legally obligated to
          retain this data for longer periods.
        </p>

        <h2>Transfer of Data</h2>
        <p>
          Your information, including Personal Data, may be transferred to — and maintained on —
          computers located outside of your state, province, country or other governmental
          jurisdiction where the data protection laws may differ from those of your jurisdiction.
        </p>
        <p>
          If you are located outside South Korea and choose to provide information to us, please
          note that we transfer the data, including Personal Data, to South Korea and process it
          there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of such information
          represents your agreement to that transfer.
        </p>
        <p>
          UniPad will take all the steps reasonably necessary to ensure that your data is treated
          securely and in accordance with this Privacy Policy and no transfer of your Personal Data
          will take place to an organization or a country unless there are adequate controls in
          place including the security of your data and other personal information.
        </p>

        <h2>Disclosure of Data</h2>

        <h3>Legal Requirements</h3>
        <p>
          UniPad may disclose your Personal Data in the good faith belief that such action is
          necessary to:
        </p>
        <ul>
          <li>To comply with a legal obligation</li>
          <li>To protect and defend the rights or property of UniPad</li>
          <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>To protect the personal safety of users of the Service or the public</li>
          <li>To protect against legal liability</li>
        </ul>

        <h2>Security of Data</h2>
        <p>
          The security of your data is important to us but remember that no method of transmission
          over the Internet or method of electronic storage is 100% secure. While we strive to use
          commercially acceptable means to protect your Personal Data, we cannot guarantee its
          absolute security.
        </p>

        <h2>
          Your Data Protection Rights under the California Online Privacy Protection Act (CalOPPA)
        </h2>
        <p>
          CalOPPA is the first state law in the nation to require commercial websites and online
          services to post a privacy policy. The law&apos;s reach stretches well beyond California
          to require a person or company in the United States (and conceivably the world) that
          operates websites collecting personally identifiable information from California consumers
          to post a conspicuous privacy policy on its website stating exactly the information being
          collected and those individuals with whom it is being shared, and to comply with this
          policy.
        </p>
        <p>According to CalOPPA we agree to the following:</p>
        <ul>
          <li>Users can visit our site anonymously</li>
          <li>
            Our Privacy Policy link includes the word &quot;Privacy&quot; and can easily be found on
            the page specified above
          </li>
          <li>
            Users will be notified of any privacy policy changes on our Privacy Policy Page
          </li>
          <li>
            Users are able to change their personal information by emailing us
          </li>
        </ul>

        <h2>Your Data Protection Rights under the General Data Protection Regulation (GDPR)</h2>
        <p>
          If you are a resident of the European Economic Area (EEA), you have certain data
          protection rights. UniPad aims to take reasonable steps to allow you to correct, amend,
          delete or limit the use of your Personal Data.
        </p>
        <p>
          If you wish to be informed about what Personal Data we hold about you and if you want it
          to be removed from our systems, please contact us.
        </p>
        <p>In certain circumstances, you have the following data protection rights:</p>
        <ul>
          <li>
            <strong>The right to access, update or delete</strong> the information we have on you.
          </li>
          <li>
            <strong>The right of rectification</strong> — you have the right to have your
            information rectified if that information is inaccurate or incomplete.
          </li>
          <li>
            <strong>The right to object</strong> — you have the right to object to our processing
            of your Personal Data.
          </li>
          <li>
            <strong>The right of restriction</strong> — you have the right to request that we
            restrict the processing of your personal information.
          </li>
          <li>
            <strong>The right to data portability</strong> — you have the right to be provided with
            a copy of the information we have on you in a structured, machine-readable and commonly
            used format.
          </li>
          <li>
            <strong>The right to withdraw consent</strong> — you also have the right to withdraw
            your consent at any time where UniPad relied on your consent to process your personal
            information.
          </li>
        </ul>
        <p>
          Please note that we may ask you to verify your identity before responding to such
          requests.
        </p>

        <h2>Service Providers</h2>
        <p>
          We may employ third party companies and individuals to facilitate our Service (&quot;Service
          Providers&quot;), provide the Service on our behalf, perform Service-related services or
          assist us in analyzing how our Service is used.
        </p>
        <p>
          These third parties have access to your Personal Data only to perform these tasks on our
          behalf and are obligated not to disclose or use it for any other purpose.
        </p>

        <h3>Analytics</h3>
        <p>
          We may use third-party Service Providers to monitor and analyze the use of our Service.
        </p>
        <ul>
          <li>
            <strong>Google Analytics</strong> — Google Analytics is a web analytics service offered
            by Google that tracks and reports website traffic. For more information on the privacy
            practices of Google, please visit the Google Privacy &amp; Terms web page:{' '}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://policies.google.com/privacy
            </a>
          </li>
          <li>
            <strong>Firebase</strong> — Firebase is an analytics service provided by Google Inc. For
            more information on what type of information Firebase collects, please visit the Google
            Privacy &amp; Terms web page:{' '}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://policies.google.com/privacy
            </a>
          </li>
        </ul>

        <h3>Advertising</h3>
        <p>
          We may use third-party Service Providers to show advertisements to you to help support and
          maintain our Service.
        </p>
        <ul>
          <li>
            <strong>AdMob by Google</strong> — AdMob by Google is provided by Google Inc. For more
            information on how Google uses the collected information, please visit the &quot;How
            Google uses data when you use our partners&apos; sites or apps&quot; page:{' '}
            <a
              href="https://policies.google.com/technologies/partner-sites"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://policies.google.com/technologies/partner-sites
            </a>
          </li>
        </ul>

        <h3>Payments</h3>
        <p>
          We may provide paid products and/or services within the Service. In that case, we use
          third-party services for payment processing.
        </p>
        <ul>
          <li>
            <strong>Google Play In-App Payments</strong> — Their Privacy Policy can be viewed at:{' '}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
            >
              https://policies.google.com/privacy
            </a>
          </li>
        </ul>

        <h2>Links to Other Sites</h2>
        <p>
          Our Service may contain links to other sites that are not operated by us. If you click a
          third party link, you will be directed to that third party&apos;s site. We strongly advise
          you to review the Privacy Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content, privacy policies or
          practices of any third party sites or services.
        </p>

        <h2>Children&apos;s Privacy</h2>
        <p>Our Service does not address anyone under the age of 13 (&quot;Children&quot;).</p>
        <p>
          We do not knowingly collect personally identifiable information from anyone under the age
          of 13. If you are a parent or guardian and you are aware that your child has provided us
          with Personal Data, please contact us. If we become aware that we have collected Personal
          Data from children without verification of parental consent, we take steps to remove that
          information from our servers.
        </p>

        <h2>Changes to This Privacy Policy</h2>
        <p>
          We may update our Privacy Policy from time to time. We will notify you of any changes by
          posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on our Service, prior to the
          change becoming effective and update the &quot;effective date&quot; at the top of this
          Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any changes. Changes to
          this Privacy Policy are effective when they are posted on this page.
        </p>

        <h2>Contact Us</h2>
        <p>If you have any questions about this Privacy Policy, please contact us:</p>
        <ul>
          <li>
            By email:{' '}
            <a href="mailto:0226unipad@gmail.com">0226unipad@gmail.com</a>
          </li>
        </ul>
      </div>
    </div>
  );
}
