"""Validates the stored data, then writes `output/coverage.json`, `output/SUPPORT_MATRIX.md` and
`output/COVERAGE_SUMMARY.md`.

Usage (from meta/compatibility): python3 scripts/compute_coverage.py [--check]
`--check` writes nothing. It exits non-zero when a raw snapshot, a derived table, the label mapping or the
matrix breaks a rule, when a coverage block is not exactly one denominator table, or when the stored output
differs from what the data gives now.
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

from build_tables import derived_problems
from compat import FEATURES, ROOT, compute_coverage, load_all, split_ids
from rules import block_problems, validate

STATUS_LABELS = {"verified_run": "run", "partial_run": "partial", "viewport_only": "width only", "source_only": "code only",
                 "unverified": "-", "failed": "FAIL", "not_applicable": "n/a"}
DECLARATION_LABELS = {"declared_supported": "decl. supported", "declared_unsupported": "decl. unsupported",
                      "not_declared": "no decl.", "not_applicable": "n/a"}
BUCKET_COLUMNS = (("verified_physical", "phys"), ("verified_emulated_sold", "emu sold"), ("verified_emulated_unsold", "emu unsold"),
                  ("partly_run", "part"), ("declared_not_run", "decl"), ("unsupported_or_failed", "unsup"), ("unknown", "unk"),
                  ("unmapped_label", "unmap"), ("not_applicable", "n/a"))


def render_matrix(data: dict) -> str:
    rows = {(r["combo_id"], r["feature"]): r for r in data["matrix"]}
    lines = [
        "# Support matrix (generated)",
        "",
        "Generated by `scripts/compute_coverage.py` from `data/support_matrix.csv`; edit the CSV, not this file.",
        "Each cell is declaration / verification. Only `run` counts as working; every other status is a gap and carries a",
        "`TODO:` in the CSV. `run` here never means a physical device: see the second table for what each run was.",
        "",
        "| Combination | Category | OS / browser | Version | " + " | ".join(f.replace("_", " ") for f in FEATURES) + " |",
        "|---|---|---|---|" + "---|" * len(FEATURES),
    ]
    for combo in data["combos"]:
        cells = [f"{DECLARATION_LABELS[rows[(combo['combo_id'], f)]['support_declaration']]} / "
                 f"{STATUS_LABELS[rows[(combo['combo_id'], f)]['verification_status']]}" for f in FEATURES]
        lines.append(f"| `{combo['combo_id']}` | {combo['device_category']} | {combo['os_or_browser']} | {combo['version_scope']} | "
                     + " | ".join(cells) + " |")
    counts = Counter(r["verification_status"] for r in data["matrix"])
    lines += ["", "Row counts by verification status: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())) + ".", "",
              "## What was actually run", "",
              "Every row where something ran, with the exact scope. `Ran on` comes from the evidence, `Sold build` says whether the",
              "tested code is contained in a build that is on sale.", "",
              "| Row | Status | Ran on | Sold build | Confirmed scope | Evidence |", "|---|---|---|---|---|---|"]
    for r in data["matrix"]:
        if r["verification_status"] in ("verified_run", "partial_run", "viewport_only", "failed"):
            lines.append(f"| `{r['row_id']}` | {STATUS_LABELS[r['verification_status']]} | {r['device_reality']} | {r['in_sold_app']} | "
                         f"{r['confirmed_scope']} | {', '.join(split_ids(r['evidence_ids']))} |")
    return "\n".join(lines) + "\n"


def render_summary(coverage: dict, data: dict) -> str:
    """One table per denominator series; each is a proxy on its own unit, never a world share of devices."""
    lines = [
        "# Coverage by denominator series (generated)",
        "",
        "World share of installed devices: **unknown** (" + coverage["world_installed_device_share_reason"] + ")",
        "",
        "Every table below is a separate denominator. Do not add, multiply or compare their percentages with each other.",
        "Columns are the share of that series' table, in the series' own unit:",
        "`phys` run on a physical device; `emu sold` run in an emulator or simulator on code that is in a build on sale;",
        "`emu unsold` the same on code that is not (or not known to be) in a build on sale; `part` something ran but not the",
        "whole feature or not the named product (a sideloaded build instead of a store install, headless Chromium instead of",
        "Chrome); `decl` declared supported, nothing run (a mocked screen width counts here); `unsup` declared unsupported or",
        "failed; `unk` no declaration; `unmap` label not tied to any combination; `n/a` feature does not apply.",
        "",
        "A combination that spans a version range (for example iOS 26.x or Android 10-14) counts as run when a version inside the",
        "range was run. The versions and devices that actually ran are named per row in `SUPPORT_MATRIX.md`; a run of some minor",
        "versions is not a check of the whole major version, of every device model, or of a physical device.",
        "",
    ]
    order: dict[tuple[str, str], list[dict]] = {}
    for b in coverage["blocks"]:
        order.setdefault((b["series_id"], b["category"]), []).append(b)
    for (sid, category), blocks in order.items():
        first = blocks[0]
        lines += [f"## {sid} / {category}", "",
                  f"- Unit: {first['unit']}", f"- Population: {first['population']}", f"- Region: {first['region']}",
                  f"- Period: {first['reference_period']}", f"- Table total: {first['table_total_percent']}", "",
                  "| Feature | " + " | ".join(title for _, title in BUCKET_COLUMNS) + " |",
                  "|---|" + "---|" * len(BUCKET_COLUMNS)]
        for b in blocks:
            lines.append(f"| {b['feature']} | " + " | ".join(str(b["buckets_percent"][key]) for key, _ in BUCKET_COLUMNS) + " |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def problems_of(data: dict) -> tuple[list[str], dict | None]:
    """Every rule in one place: stored data, derived files against the raw snapshots, blocks against tables."""
    problems = validate(data) + derived_problems(data["root"])
    if problems:
        return problems, None
    coverage = compute_coverage(data)
    return block_problems(data, coverage), coverage


def main(argv: list[str], root: Path = ROOT) -> int:
    data = load_all(root)
    problems, coverage = problems_of(data)
    if problems:
        print("\n".join(problems))
        return 1
    out = root / "output"
    texts = {
        "coverage.json": json.dumps(coverage, indent=2, ensure_ascii=False) + "\n",
        "SUPPORT_MATRIX.md": render_matrix(data),
        "COVERAGE_SUMMARY.md": render_summary(coverage, data),
    }
    if "--check" in argv:
        stale = [name for name, text in texts.items()
                 if not (out / name).exists() or (out / name).read_text(encoding="utf-8") != text]
        if stale:
            print("stale output: " + ", ".join(stale))
            return 1
        print("ok: data valid, derived files match the raw snapshots, output up to date")
        return 0
    out.mkdir(exist_ok=True)
    for name, text in texts.items():
        (out / name).write_text(text, encoding="utf-8")
    print(f"ok: {len(data['matrix'])} rows, {len(coverage['blocks'])} coverage blocks")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
