import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import JSZip from 'jszip';

const root = new URL('./', import.meta.url);
const stamp = new Date('2020-01-01T00:00:00Z');
export const sha256 = bytes => createHash('sha256').update(bytes).digest('hex');

export function tone(frequency) {
  const samples = 4410;
  const wav = Buffer.alloc(44 + samples * 2);
  wav.write('RIFF');
  wav.writeUInt32LE(wav.length - 8, 4);
  wav.write('WAVEfmt ', 8);
  wav.writeUInt32LE(16, 16);
  wav.writeUInt16LE(1, 20);
  wav.writeUInt16LE(1, 22);
  wav.writeUInt32LE(44100, 24);
  wav.writeUInt32LE(88200, 28);
  wav.writeUInt16LE(2, 32);
  wav.writeUInt16LE(16, 34);
  wav.write('data', 36);
  wav.writeUInt32LE(samples * 2, 40);
  for (let i = 0; i < samples; i++) {
    wav.writeInt16LE(Math.round(Math.sin(i * 2 * Math.PI * frequency / 44100) * 4000), 44 + i * 2);
  }
  return wav;
}

export async function artifacts() {
  const files = new Map();
  for (const [name, frequency] of Object.entries({ a: 440, b: 660, c: 880 })) {
    files.set(`sources/sounds/${name}.wav`, tone(frequency));
  }
  for (const name of ['manual', 'delayed']) {
    const zip = new JSZip();
    for (const file of ['info', 'keySound']) {
      const path = `sources/${name}/${file}`;
      const bytes = await readFile(new URL(path, root));
      files.set(path, bytes);
      zip.file(file, bytes, { date: stamp, createFolders: false });
    }
    for (const [path, bytes] of files) {
      if (path.startsWith('sources/sounds/')) {
        zip.file(path.slice('sources/'.length), bytes, { date: stamp, createFolders: false });
      }
    }
    files.set(`packs/${name}.uni`, await zip.generateAsync({ type: 'nodebuffer', compression: 'STORE', platform: 'DOS' }));
  }
  files.set('expectations.json', await readFile(new URL('expectations.json', root)));
  const manifest = {
    suite: 'chain-release-v1',
    hash: 'sha256',
    files: Object.fromEntries([...files].sort(([a], [b]) => a.localeCompare(b)).map(([path, bytes]) =>
      [path, { bytes: bytes.length, sha256: sha256(bytes) }])),
  };
  files.set('manifest.json', Buffer.from(JSON.stringify(manifest, null, 2) + '\n'));
  return files;
}

export async function checkArtifacts(directory = root) {
  const files = await artifacts();
  for (const [path, bytes] of files) {
    const actual = await readFile(new URL(path, directory));
    if (!actual.equals(bytes)) throw new Error(`Generated bytes differ: ${path}`);
  }
  if ((await readdir(directory)).sort().join(',') !==
      'README.md,corpus.test.mjs,expectations.json,generate.mjs,manifest.json,packs,sources') {
    throw new Error('Unexpected corpus entry');
  }
  if ((await readdir(new URL('sources/', directory))).sort().join(',') !== 'delayed,manual,sounds') {
    throw new Error('Unexpected source entry');
  }
  for (const name of ['manual', 'delayed']) {
    const entries = await readdir(new URL(`sources/${name}/`, directory));
    if (entries.sort().join(',') !== 'info,keySound') throw new Error(`Unexpected source file: ${name}`);
  }
  if ((await readdir(new URL('packs/', directory))).sort().join(',') !== 'delayed.uni,manual.uni') {
    throw new Error('Unexpected pack file');
  }
  if ((await readdir(new URL('sources/sounds/', directory))).sort().join(',') !== 'a.wav,b.wav,c.wav') {
    throw new Error('Unexpected audio file');
  }
  return files.size;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv[2] === '--check') {
    console.log(`chain-release-v1: ${await checkArtifacts()} files verified; no platform playback verdict`);
  } else if (process.argv.length === 2) {
    const files = await artifacts();
    for (const [path, bytes] of files) {
      await mkdir(new URL('./', new URL(path, root)), { recursive: true });
      await writeFile(new URL(path, root), bytes);
    }
    console.log(`chain-release-v1: ${files.size} files generated`);
  } else {
    throw new Error('Usage: node generate.mjs [--check]');
  }
}
